meldippw/urls.py
from django.contrib import admin
from django.urls import path, include
from tugas.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('tugas.urls')),
]

tugas/urls.py
from django.urls import include, path
from . import views
from django.shortcuts import render
from django.conf.urls import url

app_name= 'tugas'

urlpatterns = [
    path('',views.home,name='index'),
    path('projects/', views.projects,name=('projects')),
    path('background/', views.background ,name=('background')),
    path('contacts/',  views.contacts,name='contacts'),
    path('jadwal/',views.jadwal,name='jadwal'),
    path('delete/<int:delete_id>',views.deleteJadwal,name='deleteJadwal'),
]

tugas/models.py
from django.db import models

# Create your models here.

class jadwalModel(models.Model):
	tanggal = models.DateField()
	kegiatan = models.TextField(max_length =21)
	tempat = models.CharField(max_length=20)
	kategori = models.CharField(max_length=20)

	def __str__(self):
		return "{}. {}".format(self.id,self.kegiatan)

tugas/forms.py
from django import forms
from . import models

##Create your forms here

class jadwalKegiatan(forms.Form):
	
	tanggal = forms.DateField(required = True,
		widget= forms.SelectDateWidget)
	kegiatan = forms.CharField(max_length = 20)
	tempat = forms.CharField(max_length=20)
	kategori = forms.CharField(max_length=20)

tugas/views.py
from django.shortcuts import render,redirect
from .models import jadwalModel
from .forms import jadwalKegiatan

# Create your views here.
def home(request):
    return render(request,'pages/index.html',{})
def projects(request):
    return render(request,'pages/projects.html',{})
def background(request):
    return render(request,'pages/background.html',{})
def contacts(request):
    return render(request,'pages/contacts.html',{})
def jadwal(request):
	createJadwal = jadwalKegiatan(request.POST or None)
	jadwals = jadwalModel.objects.all()
	context= {
		'jadwals':jadwals,
		'create_jadwal':createJadwal,
	}
	if request.method == 'POST':
		if createJadwal.is_valid():
			jadwalModel.objects.create(
				tanggal 	= createJadwal.cleaned_data.get('tanggal'),
				kegiatan 	= createJadwal.cleaned_data.get('kegiatan'),
				tempat 		= createJadwal.cleaned_data.get('tempat'),
				kategori 	= createJadwal.cleaned_data.get('kategori'),
				)
	return render(request,'pages/jadwal.html',context)
def deleteJadwal(request, delete_id):
	jadwalModel.objects.filter(id=delete_id).delete()
	return redirect("tugas:jadwal")

tugas/templates/baseNav.html
<!DOCTYPE html>
{%load static%}

{%block content%}
<div class="fooheader"></div>
  <nav class="nav nav-black justify-content-end fixed-top">
    <a class="nav-link nav-link-white active" href="{% url 'tugas:index' %}">About</a>
    <a class="nav-link nav-link-white" href="{% url 'tugas:background' %}">Background</a>
    <a class="nav-link nav-link-white" href="{% url 'tugas:contacts' %}">Contact</a>
    <a class="nav-link nav-link-white" href="{% url 'tugas:projects' %}">Project</a>
    <a class="nav-link nav-link-white" href="{% url 'tugas:jadwal' %}">Jadwal</a>
    <a class="navbar-brand justify-content-start" href="#">
      <img id="img-size" src="https://i.ibb.co/7Qkkf5y/logo.png" alt="">
  </a>
  </nav>
  {%endblock%}
</html>

tugas/templates/pages/background.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>Meldi's Background</title>
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/styling.css' %}">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
{% include "baseNav.html" %}

    <div id="Background" class="Background">
    <h3 class="text-center font-white mx-auto">Background</h3>
    <div class="top-background text-center font-white mx-auto"><h5>Education</h5>
      <div class="text-center font-white mx-auto">
        <div class="text-center font-white mx-auto justify-content">
          <h6>SD Kartika VIII-2</h6>
          <h6>SMPN 20 Jakarta</h6>
          <h6>SMAN 48 Jakarta</h6>
          <h6>Universitas Indonesia</h6>
        </div>
      </div>
    </div>

    <div class="d-flex low-background justify-content-around">
      <div class="font-white">Volunteering Experience
          <h5>BEM Fasilkom UI 2019<br />
            <span>Staff Dept. Pengabdian Masyarakat</span>
          </h5>
          <h5>FUKI Fasilkom UI 2019<br />
            <span>Kepala Dept. Sosial Masyarakat</span>
          </h5>
          <h5>BEM Fasilkom UI 2018<br />
            <span>Project Officer of SPACE 2018</span>
          </h5>
          <h5>Rohis 48<br />
            <span>Mentor</span>
          </h5>
          <h5>DDP-0<br />
            <span>Mentor</span>
          </h5>
      </div>
      <div class="font-white">Professional Experience
          <h5>Universitas Indonesia<br />
            <span>Teaching Assistant for DDP-1 Course.</span>
          </h5>
      </div>
    </div>

  </div>


</body>
</html>

tugas/templates/pages/baseNav.html
<!DOCTYPE html>

<div class="fooheader"></div>
  <nav class="nav nav-black justify-content-end fixed-top">
    <a class="nav-link nav-link-white active" href="{% url 'tugas:index' %}">About</a>
    <a class="nav-link nav-link-white" href="{% url 'tugas:background' %}">Background</a>
    <a class="nav-link nav-link-white" href="{% url 'tugas:contacts' %}">Contact</a>
    <a class="nav-link nav-link-white" href="{% url 'tugas:jadwal' %}">Jadwal</a>
    <a class="navbar-brand justify-content-start" href="#">
      <img id="img-size" src="https://i.ibb.co/7Qkkf5y/logo.png" alt="">
  </a>
  </nav>
</html>

tugas/templates/pages/contacts.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/styling.css' %}">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Contact</title>
</head>
<body>
{% include "baseNav.html" %}

   <div id="Contact" class="Contact text-center">
  	<h3 class="text-center mx-auto">Contact</h3>
    <a href="https://bit.ly/ThisIsMeldi" class="btn btn-floating btn-lg btn-social-icon btn-linkedin">
      <i class="fa fa-linkedin"></i>
    </a>
    <a href="https://instagram.com/meldihaf_" class="btn btn-floating btn-lg btn-social-icon btn-instagram">
      <i class="fa fa-instagram"></i>
    </a>
    <a href="mailto:meldihafizh@gmail.com" class="btn btn-floating btn-lg btn-social-icon btn-email">
      <i class="fa fa-envelope"></i>
    </a>

  </div>

</body>
</html>

tugas/templates/pages/index.html
{% load static %}
<HTML>
<head>
  <title>Meldi's Profile Page</title>
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/styling.css' %}">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<main>
    {% include "baseNav.html" %}
  <div  id="profile-page" class="profile-page">
    <img id="its-me" src="https://i.ibb.co/T04Hvxk/IMG-1353-min.jpg" class="mx-auto d-block shadow" alt="pic">
    <h3 class="text-center mx-auto help font-white">Meldi Hafizh Sayoko</h3>
  </div>

  <div class="container text-center mx-auto justify-content-around">
  	<div class="row">
      <div class="column text-center mx-auto"><h3>About Me</h3></div>
    </div>
    <div class="row">
      <div class="column about-me-text mx-auto text-center justify-content-around">A student at Universitas Indonesia with an enormous passion for technology. Also like communicating and connecting people, also active in Social Service activities. Born in Jakarta at 27th of January 2000.</div>
    </div>
  </div>

</main>

tugas/templates/pages/jadwal.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  	<link rel="stylesheet" type="text/css" href="{% static 'css/styling.css' %}">
  	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>ini Jadwal</title>
</head>
<body>
	{% include "baseNav.html" %}
	<br>
	<br>
	<br>
	<form method="POST">
		{% csrf_token %}
		<table>
      {{create_jadwal.as_table}}
			<button type="Submit">Kirim</button>
		</table>
	</form>
	<br>
	<br>
	<table class="table table-dark table-striped">
  <thead>
    <tr>
      <th scope="col">Tanggal</th>
      <th scope="col">Kegiatan</th>
      <th scope="col">Kategori</th>
      <th scope="col">Tempat</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
  	{% for jadwal in jadwals %}
    <tr>
      <th scope="row">{{jadwal.tanggal}}</th>
      <td>{{jadwal.kegiatan}}</td>
      <td>{{jadwal.kategori}}</td>
      <td>{{jadwal.tempat}}</td>
      <td><a class='btn btn-warning' href="{% url 'tugas:deleteJadwal' delete_id=jadwal.id %}" title=''>Delete<a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
</body>
</html>

tugas/templates/pages/projects.html
<!DOCTYPE html>
<html class="Warnahtml">
<head>
	<title>Meldi's Project</title>
	<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link href="styling.css" rel="stylesheet" type="text/css">
</head>
{% include "baseNav.html" %}
<body class="Warnahtml center-page">
	<div class="text-center mx-auto font-white">
		<h1>Projects</h1>
		<h2>Coming Soon</h2>
		<div class="progress text-center mx-auto">
  		<div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width: 50%"></div>
			</div>
	 </div>
</body>
</html>